language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database naschmarkt_testing;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit